# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y enchant

install: 
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - py.test
